version: '3'

services:
  main:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    # override the default of erl as we want to run tests
    entrypoint: bash
    stdin_open: true
    tty: true
